{% set name = "ciecplib" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc115e315b6a9d38e7613ddb43a140dec0261595ffddbf82621a980cc17cd141

build:
  entry_points:
    - ecp-cert-info = ciecplib.tool.ecp_cert_info:main
    - ecp-curl = ciecplib.tool.ecp_curl:main
    - ecp-get-cert = ciecplib.tool.ecp_get_cert:main
    - ecp-get-cookie = ciecplib.tool.ecp_get_cookie:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=30.3.0
    - argparse-manpage
    - m2crypto
    - pyopenssl
    - requests
    - requests-ecp
  run:
    - m2crypto
    - pyopenssl
    - python >=3.5
    - requests
    - requests-ecp

test:
  requires:
    - pip
    - pytest >=3.9.0
    - requests-mock
  commands:
    # check dependencies
    - python -m pip check
    # run automated tests
    - python -m pytest --pyargs ciecplib
    # validate entry points
    - ecp-cert-info --help
    - ecp-curl --help
    - ecp-get-cert --help
    - ecp-get-cookie --help
    # sanity check manuals
    - man -M ${PREFIX}/share/man -w ecp-get-cert

about:
  home: https://ciecplib.readthedocs.io
  doc_url: https://ciecplib.readthedocs.io
  dev_url: https://github.com/duncanmmacleod/ciecplib/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python client for SAML ECP authentication
  description: |
    This python package provides a native Python client to access
    SAML/ECP-authenticated content over HTTP with CILogon.

extra:
  recipe-maintainers:
    - duncanmmacleod
